---
title: "Assignment01"
author: "Soyeon Hwang"
date: \today
output:
  pdf_document: 
    number_sections: yes
  latex-engine : xelatex
header-includes:
   \usepackage{kotex}
mainfont: NanumGothic
fontsize: 12pt
editor_options:
  chunk_output_type: console
---

```{r, include=FALSE, echo = TRUE, results = 'hide', warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Basic Commands 
### vector
```{r}
x = c(1, 3, 2, 5) ; x
```

```{r}
x = c(1, 6, 2) ; x
y = c(1, 4, 3)
```

### length
```{r}
length(x) ; length(y)
x + y
```

```{r}
ls()
```

### remove
```{r}
rm(x, y)
ls()
```

```{r}
rm(list = ls())
```

### matrix
```{r}
?matrix
```

```{r}
x = matrix(data = c(1, 2, 3, 4), nrow = 2, ncol = 2)
x
```

```{r}
x = matrix(c(1, 2, 3, 4), 2, 2)
x
```

### square root
```{r}
sqrt(x)
```

```{r}
x^2
```

### rnorm, cor
```{r}
x = rnorm(50)
y = x + rnorm(50, mean = 50, sd = 0.1)
cor(x, y)
```

### set.seed
```{r}
set.seed(1303)
rnorm(50)
```

### mean, var, sd
```{r}
set.seed(3)
y = rnorm(100)
mean(y) ; var(y) ; sqrt(var(y)) ; sd(y)
```

# Graphics
### plot
```{r}
x = rnorm(100)
y = rnorm(100)
plot(x, y)
plot(x, y,
     xlab = "this is the x-axis", 
     ylab = "this is the y-axis", 
     main = "Plot of X vs Y")
```

### pdf(), jpeg()
```{r}
pdf("Figure.pdf")
plot(x, y, col = "green")
dev.off()
```

### seq()
```{r}
x = seq(1, 10) ; x
x = 1:10 ; x
x = seq(-pi, pi, length = 50) ; x
```

### contour()
```{r}
y = x
f = outer(x, y, function(x, y) cos(y) / (1 + x^2))
contour(x, y, f)
contour(x, y, f, nlevels = 45, add = T)
fa = (f - t(f)) / 2
contour(x, y, fa, nlevels = 15)
```

### persp()
```{r}
image(x, y, fa)
persp(x, y, fa)
persp(x, y, fa, theta = 30)
persp(x, y, fa, theta = 30, phi = 20)
persp(x, y, fa, theta = 30, phi = 70)
persp(x, y, fa, theta = 30, phi = 40)
```

# Indexing Data
### indices in matrix
```{r}
A = matrix(1:16, 4, 4)
A
A[2, 3]
```

```{r}
A[c(1, 3), c(2, 4)]
A[1:3, 2:4]
A[1:2, ]
A[, 1:2]
```

```{r}
A[1, ]
```

```{r}
A[-c(1, 3), ]
```

### dim()
```{r}
dim(A)
```

# Loading data
### read.table()
```{r}
Auto = read.table("Auto.data")
fix(Auto)
```

```{r}
Auto = read.table("Auto.data", header = T, na.strings = "?")
fix(Auto)
```

### read.csv()
```{r}
Auto = read.csv("Auto.csv", header = T, na.strings = "?")
fix(Auto)
dim(Auto)
Auto[1:4, ]
```

### na.omit()
```{r}
Auto = na.omit(Auto)
dim(Auto)
```

### names()
```{r}
names(Auto)
```

# Additional Graphical and Numerical Summaries
```{r}
library(ISLR)
data(Auto)
plot(Auto$cylinders, Auto$mpg)
```

### attach()
```{r}
attach(Auto)
plot(cylinders, mpg)
```

### as.factor()
```{r}
cylinders = as.factor(cylinders)
```

### boxplot
```{r}
plot(cylinders, mpg)
plot(cylinders, mpg, col = "red")
plot(cylinders, mpg, col = "red", varwidth = T)
plot(cylinders, mpg, col = "red", varwidth = T, 
     xlab = "cylinders", ylab = "NPG")
```

### hist()
```{r}
hist(mpg)
hist(mpg, col = 2)
hist(mpg, col = 2, breaks = 15)
```

### pairs()
```{r}
pairs(Auto)
pairs(~ mpg + displacement + horsepower + weight + acceleration, 
      Auto)
```

### identify()
```{r}
plot(horsepower, mpg)
identify(horsepower, mpg, name)
```

### summary()
```{r}
summary(Auto)
```

```{r}
summary(mpg)
```




